name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_NAME: test_db
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r messaging_app/requirements.txt
        pip install pytest pytest-django mysqlclient flake8 pytest-cov

    - name: Lint code with flake8
      run: |
        . venv/bin/activate
        flake8 messaging_app --exit-zero
      continue-on-error: false  # Fail the build on lint errors

    - name: Run Django Tests with Coverage
      run: |
        . venv/bin/activate
        pytest messaging_app/tests --cov=messaging_app --cov-report=xml --junitxml=report.xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: report.xml
