#!/bin/bash

# Deploy blue version
kubectl apply -f blue_deployment.yaml

# Deploy green version
kubectl apply -f green_deployment.yaml

# Apply the service (pointing to green initially)
kubectl apply -f kubeservice.yaml

# Check logs of green pods
GREEN_POD=$(kubectl get pods -l app=django-messaging-app-green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
