apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  selector:
    app: django-messaging-app-blue   
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
